version: "3.3"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    restart: unless-stopped
    environment:
      - PUID=${PUID_PIWIGO}
      - PGID=${PGID_PIWIGO}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/piwigo:/config
      - ${CONFIG}/piwigo/pictures:/pictures
    ports:
      - ${PIWIGO_HTTP}:80
    networks:
      - intranet
      - web
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.piwigo-web.rule=Host(`${PIWIGO_DOMAIN}`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.piwigo-web.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.piwigo-web.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.piwigo-secured.rule=Host(`${PIWIGO_DOMAIN}`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.piwigo-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.piwigo-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
    depends_on: 
      - piwigo-db

  piwigo-db:
    image: linuxserver/mariadb
    container_name: piwigo-db
    restart: unless-stopped
    environment:
      - PUID=${PUID_PIWIGO}
      - PGID=${PGID_PIWIGO}
      - MYSQL_USER=${PIWIGO_MYSQL_USER}  
      - MYSQL_DATABASE=${PIWIGO_MYSQL_DATABASE}
      - MYSQL_PASSWORD=${PIWIGO_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PIWIGO_MYSQL_ROOT_PASSWORD}
    volumes:
      - ${CONFIG}/piwigo-db:/config
    ports:
      - ${PIWIGO_DB_PORT}:3306
    networks:
      - intranet

networks:
  web:
    external: true
  intranet:
    external: true
