version: "3.3"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=${PUID_NEXTCLOUD}
      - PGID=${PGID_NEXTCLOUD}
      - TZ=${TZ}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      #- TRUSTED_PROXIES=
    volumes:
      - /data/nextcloud:/data
      - ${CONFIG}/nextcloud/app:/var/www/html #during gui install, select /data as data folder
    ports:
      - ${NEXTCLOUD_HTTPS}:80
    depends_on:
      - nextclouddb    
    networks:
      - intranet
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-web.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-web.entrypoints=web"
      - "traefik.http.routers.nextcloud-web.middlewares=redirect@file"
      - "traefik.http.routers.nextcloud-secured.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secured.entrypoints=web-secured"
      - "traefik.http.routers.nextcloud-secured.tls.certresolver=mytlschallenge"

  nextclouddb:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - PUID=${PUID_NEXTCLOUD}
      - PGID=${PGID_NEXTCLOUD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/nextcloud/db:/config
    ports:
      - ${NEXTCLOUD_DB_PORT}:3306
    networks:
      - intranet

networks:
  web:
    external: true
  intranet:
    external: true