version: "3.3"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=${PUID_NEXTCLOUD}
      - PGID=${PGID_NEXTCLOUD}
      - TZ=${TZ}
    volumes:
      -  ${CONFIG}/nextcloud:/config
      - /data/nextcloud:/data
    ports:
      - ${NEXTCLOUD_HTTPS}:443
    depends_on:
      - nextclouddb

  nextclouddb:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - PUID=${PUID_NEXTCLOUD}
      - PGID=${PGID_NEXTCLOUD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/nextcloud/db:/config
    ports:
      - ${NEXTCLOUD_DB_PORT}:3306

networks:
  default:
    external:
      name: intranet
