version: "3.3"

services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - ${MEDIA_DOWNLOADS}:/downloads 
      - ${CONFIG}/deluge:/config 
    ports:
      - ${DELUGE_HTTP}:8112
      - ${DELUGE_DAEMON}:58846
      - ${DELUGE_INCOMING}:58946
      - ${DELUGE_INCOMING}:58946/udp
    networks:
      - intranet

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DOWNLOADS}/torrent-blackhole:/downloads 
      - ${CONFIG}/jackett:/config 
    ports:
      - ${JACKET_HTTP}:9117
    networks:
      - intranet

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/sonarr:/config 
      - ${MEDIA_TV}:/tv 
      - ${MEDIA_DOWNLOADS}:/downloads 
    ports:
      - ${SONAR_HTTP}:8989
    networks:
      - intranet

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/radarr:/config 
      - ${MEDIA_MOVIES}:/movies 
      - ${MEDIA_DOWNLOADS}:/downloads 
    ports:
      - ${RADARR_HTTP}:7878
    networks:
      - intranet

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} 
      #- PLEX_CLAIM=#Put here the key from https://plex.tv/claim (4 minutes expiry, needed for first start only)
    tmpfs: /transcode
    volumes:
      - ${CONFIG}/plex/db:/config 
      - ${MEDIA_MOVIES}:/data/movies 
      - ${MEDIA_TV}:/data/tv 
    ports:
      - ${PLEX_WEB}:32400
      - ${PLEX_WEB}:32400/udp
      - ${PLEX_DLNA_TCP}:32469
      - ${PLEX_DLNA_TCP}:32469/udp
      - ${PLEX_DISC}:5353/udp
      - ${PLEX_DLNA_UDP}:1900/udp
    networks:
      - intranet
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex-web.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex-web.rule=Host(`${PLEX_DOMAIN}`)"
      - "traefik.http.routers.plex-web.entrypoints=web"
      - "traefik.http.routers.plex-web.middlewares=redirect@file"
      - "traefik.http.routers.plex-secured.rule=Host(`${PLEX_DOMAIN}`)"
      - "traefik.http.routers.plex-secured.entrypoints=web-secured"
      - "traefik.http.routers.plex-secured.tls.certresolver=mytlschallenge"

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - ${CONFIG}/bazarr:/config 
      - ${MEDIA_MOVIES}:/movies 
      - ${MEDIA_TV}:/tv 
    ports:
      - ${BAZARR_HTTP}:6767
    networks:
      - intranet

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
      - BASE_URL=${OMBI_BASE_URL} 
    volumes:
      - ${CONFIG}/ombi:/config
    ports:
      - ${OMBI_HTTP}:3579
    networks:
      - intranet
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi-web.rule=Host(`${OMBI_DOMAIN}`)"
      - "traefik.http.routers.ombi-web.entrypoints=web"
      - "traefik.http.routers.ombi-web.middlewares=redirect@file"
      - "traefik.http.routers.ombi-secured.rule=Host(`${OMBI_DOMAIN}`)"
      - "traefik.http.routers.ombi-secured.entrypoints=web-secured"
      - "traefik.http.routers.ombi-secured.tls.certresolver=mytlschallenge"

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID_MEDIA} 
      - PGID=${PGID_MEDIA} 
      - TZ=${TZ} 
    volumes:
      - ${CONFIG}/tautulli:/config 
      - ${CONFIG}/plex/db/Library/Application Support/Plex Media Server/Logs:/logs:ro 
    ports:
      - ${TAUTULLI_HTTP}:8181
    networks:
      - intranet
      
networks:
  web:
    external: true
  intranet:
    external: true